# Generated by Django 4.2.3 on 2024-07-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0003_alter_casa_cascodblo_alter_casa_casesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='MunNumViv',
            field=models.IntegerField(db_column='MunNumViv', default=0, null=True, verbose_name='Número de Viviendas'),
        ),
    ]
