# Generated by Django 4.2.3 on 2024-07-14 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0004_alter_municipio_munnumviv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagotributario',
            name='PagTriFec',
            field=models.DateField(db_column='PagTriFec', default=django.utils.timezone.now, verbose_name='Pago Tributario Fecha emitida'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='ProPagTri',
            field=models.DecimalField(db_column='ProPagTri', decimal_places=2, default=0, max_digits=8, verbose_name='Pago Tributario'),
        ),
    ]
