# Generated by Django 4.2.3 on 2024-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0005_alter_pagotributario_pagtrifec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='MunNom',
            field=models.CharField(db_column='MunNom', max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='region',
            name='RegNom',
            field=models.CharField(db_column='RegNom', max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='TipPerDes',
            field=models.CharField(db_column='TipPerDes', max_length=15, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipovivienda',
            name='TipVivDes',
            field=models.CharField(db_column='TipVivDes', max_length=15, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='zonaurbana',
            name='ZonNom',
            field=models.CharField(db_column='ZonNom', max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='casa',
            unique_together={('CasEsc', 'CasCodBlo', 'CasPla', 'CasNumPue')},
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together={('VivCal', 'VivNum')},
        ),
    ]
