# Generated by Django 4.2.3 on 2024-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0006_alter_municipio_munnom_alter_region_regnom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='VivCodPos',
            field=models.IntegerField(db_column='VivCodPos', max_length=4, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='VivNum',
            field=models.IntegerField(db_column='VivNum', max_length=2, verbose_name='Número'),
        ),
    ]
