# Generated by Django 4.2.3 on 2024-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0007_alter_vivienda_vivcodpos_alter_vivienda_vivnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='VivCodPos',
            field=models.CharField(db_column='VivCodPos', max_length=4, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='VivNum',
            field=models.CharField(db_column='VivNum', max_length=2, verbose_name='Número'),
        ),
    ]
