# Generated by Django 4.2.3 on 2024-07-14 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0008_alter_vivienda_vivcodpos_alter_vivienda_vivnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='VivCal',
            field=models.CharField(db_column='VivCal', max_length=3, validators=[django.core.validators.MaxLengthValidator(3)], verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='VivCodPos',
            field=models.CharField(db_column='VivCodPos', max_length=4, validators=[django.core.validators.MaxLengthValidator(4)], verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='VivNum',
            field=models.CharField(db_column='VivNum', max_length=2, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='Número'),
        ),
    ]
