# Generated by Django 4.2.3 on 2024-07-14 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0010_alter_casa_cascodblo_alter_casa_casesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='CasCodBlo',
            field=models.CharField(blank=True, db_column='CasCodBlo', default=' ', max_length=2, null=True, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='Código de Bloque'),
        ),
    ]
