# Generated by Django 4.2.3 on 2024-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0011_alter_casa_cascodblo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='CasMet',
            field=models.DecimalField(db_column='CasMet', decimal_places=2, max_digits=7, verbose_name='Metros'),
        ),
    ]
