# Generated by Django 4.2.3 on 2024-07-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0013_alter_persona_pernom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='ProPagTri',
        ),
        migrations.AddField(
            model_name='pagotributario',
            name='PagTriIngFam',
            field=models.DecimalField(db_column='PagTriIngFam', decimal_places=2, default=0, max_digits=6, verbose_name='Ingreso Familiar'),
        ),
        migrations.AlterField(
            model_name='pagotributario',
            name='PagTriEstReg',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('pagada', 'Pagada'), ('debe', 'Debe')], db_column='PagTriEstReg', default='debe', max_length=15, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='ProMonIngFam',
            field=models.DecimalField(db_column='ProMonIngFam', decimal_places=2, default=0, max_digits=10, verbose_name='Monto Ingreso Familiar'),
        ),
    ]
