# Generated by Django 4.2.3 on 2024-07-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0014_remove_propietario_propagtri_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagotributario',
            unique_together={('CasCod',)},
        ),
    ]
